#!/bin/sh
#
# Gradle start up script for POSIX generated by Gradle.
#
APP_HOME=$(cd -P -- "$(dirname -- "$0")" > /dev/null && pwd -P) || exit
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ -n "$JAVA_HOME" ] ; then
    JAVACMD=$JAVA_HOME/bin/java
else
    JAVACMD=java
fi

if [ ! -f "$CLASSPATH" ] ; then
    echo "gradle-wrapper.jar is missing."
    echo "Run 'gradle wrapper --gradle-version 8.9' once, or open the project in Android Studio,"
    echo "which regenerates it automatically."
    exit 1
fi

exec "$JAVACMD" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
